---
title: "Recitation notes - week 8"
output: html_notebook
---



```{r}

nectar <- read.csv("BeeNectar.csv")
head(nectar)

table(nectar$Colony)

nectar2<-subset(nectar, Colony!=22)

str(nectar2) # tells you the class of vectors within the dataframe

nectar2$Colony <- as.factor(nectar2$Colony)
class(nectar2$Colony)


```

```{r}

m1 <- aov(Nectar ~ Colony, data = nectar2) # running an ANOVA test
m1

anova(m1) # analysis of variance test

.00115125/0.00042769

names(m1)  

norm.test <- data.frame( model1 = m1$residuals,)
norm.test

hist(norm.test$model1)

shapiro.test(norm.test$model1)
qqnorm(norm.test$model1, datax=T)
qqline(norm.test$model1, datax = T)

m2 <- aov(log(Nectar) ~ Colony, data = nectar2)
anova(m2)

norm.test <- data.frame( model1 = m1$residuals,
                         model2 = m2$residuals)
norm.test

hist(norm.test$model2)
qqnorm(norm.test$model2, datax = T) ;
qqline(norm.test$model2, datax = T)

shapiro.test(norm.test$model2)

m3 <- aov(sqrt(Nectar) ~ Colony, data = nectar2)

norm.test <- data.frame( model1 = m1$residuals,
                         model2 = m2$residuals,
                         model3 = m3$residuals)

shapiro.test(norm.test$model3)

library(car)
with(nectar2, leveneTest(Nectar, group=Colony))
with(nectar2, leveneTest(log(Nectar), group=Colony)) # Wins, but not normally distributed
with(nectar2, leveneTest(sqrt(Nectar), group= Colony))


m4 <- kruskal.test(Nectar ~ Colony, data = nectar2)
m4
```











