---
title: "Week 12 + Recitation notes"
output: html_notebook
---

Libraries that we are using today:

```{r Libraries}

library(ggplot2)

```

### Enter data

```{r}

lion <- read.csv("LionAge.csv")
head(lion) # look at our dataset

with(lion, 
     plot(proportion.black, age))

cor <- cor.test(lion$proportion.black, lion$age, method = "pearson") # pearson correlation coefficient
cor

cor$estimate^2 # R-squared

cor.sp <- cor.test(lion$proportion.black, lion$age, method = "spearman") # spearman correlation coefficient
cor.sp

```

# Running a linear regression

```{r}

m1 <- lm(age ~ proportion.black, data = lion) # does proportion.black predict male lion's age

str(lion) # both variables are numeric, if one was a factor especially proportion.black, Y then we'd be running an ANOVA or t-test

m1

# residual plots
lion$residuals <- m1$residuals # residuals from our model, m1
head(lion)

# Base R plotting
with(lion, 
     plot(proportion.black, residuals, xlab = "Proportion black on nose", ylab = "Residuals", ylim = c(-4, 4)))
abline(h = 0, lty = 2) # line type to be dotted


# ggplot 
ggplot(lion) + # with our data, lion
  geom_point(aes(x = proportion.black, y = residuals)) + # create a scatterplot of our data
  geom_hline(aes(yintercept = 0)) # this creates a line at 0 on the x axes

# testing other assumptions

par(mfrow=c(2,2)) # plots the next four graphs in a matrix of 2,2
plot(m1)  # 1. Residuals vs fitted - checks to see if residuals are linear (is the red line horizontal or close to the dotted line)
          # 2. QQ plot - are your data normally distributed, do they follow the line
          # 3. Scale-location - testing for homoscedasicity, are your residuals evenly spread around the zero line
          # 4. Residuals vs leverage - are there any influential data points, these points will be within the red dotted lines, e.g. point 30. 

mean(lion$residuals) # yes, the mean of our residuals is ~ 0, therefore equal variance
mean(m1$residuals) # from your model

summary(m1) # coefficients - p values are whether the intercept and slope are significantly different from 0 (t statistic) 
anova(m1) 


```



### Plot model results


```{r}

# 1. Base R plotting

prop.vals <- seq(min(lion$proportion.black), max(lion$proportion.black), length.out = 100)
prop.vals1 <- seq(0, 1, 0.01)
  
names(m1) # tells us the output names of our function
m1$coefficients # two coefficients from our linear model

function.age <- m1$coefficient[1] + m1$coefficient[2] * prop.vals1
pred.age <- predict(m1, # predict values from our model, m1
                    newdata = data.frame(proportion.black = prop.vals1),# give it new data from our vector of proportion black, i.e. data we want to feed into our equation
                    interval = "confidence") # confidence intervals

names(pred.age)
pred.age

with(lion, plot(proportion.black, age, xlab = "Proportion of noses black" , ylab = "Age (years)", pch = 19, xlim=c(0, 1))) # plotting the raw data
points(prop.vals1, function.age, type = "l") # plot our predicted values as a line  
polygon(c(prop.vals1, rev(prop.vals1)),
        c(pred.age[,2], rev(pred.age[,3])), border = NA, col = adjustcolor("cornflowerblue", alpha = 0.5))

### ggplot version

ggplot(lion, aes(x = proportion.black, y = age)) + # define our x and y variables in our dataset, lion
  geom_point() + # scatterplot 
  geom_smooth(method = "lm", # line of best fit as a linear model
              se = T,  # create confidence interval bands
              color = "black" ,  # line of best fit as black
              fill = "cornflowerblue") + # CIs as blue
  labs(x = "Proportion black", y = "Age (years)") 

```






