---
title: "Week 7 Recitation in-class"
author: "Natalie & Eric"
output: html_notebook
---
```{r}
rnorm(1)
```

*A random number: `r rnorm(1)`*
**bold**

```{r}
library(ggplot2)

ggplot(sleep) +
  geom_histogram(aes(x = extra), bins = 5) +
  facet_wrap("group", dir = "v") +
  labs(x = "Extra Sleep", title = "title")
```

```{r}
library(ggformula)
ggplot(sleep) +
  geom_qq(aes(sample = extra)) +
  coord_flip() +
  stat_qqline(aes(sample = extra)) +
  facet_wrap("group", dir = "h")
```

```{r}
shapiro.test(sleep$extra[sleep$group == 1])
shapiro.test(sleep$extra[sleep$group == 2])
```

```{r}
library(car)
leveneTest(extra ~ group, data = sleep)
```


```{r}
trees

ggplot(trees) +
  geom_histogram(aes(x = Volume), bins = 7)
```


```{r}
ggplot(trees, aes(sample = Volume)) +
  geom_qq() +
  stat_qqline() +
  coord_flip()


ggplot(trees) +
  geom_qq(aes(sample = Volume)) +
  stat_qqline(aes(sample = Volume)) +
  coord_flip()
```

```{r}
ggplot(trees, aes(sample = log(Volume))) +
  geom_qq() +
  stat_qqline() +
  coord_flip()

ggplot(trees) +
  geom_histogram(aes(x = log(Volume)), bins = 7)

trees$ln.Volume <- log(trees$Volume)
trees$sqrt.Volume <- sqrt(trees$Volume)
trees
```

```{r}
shapiro.test(trees$Volume)
shapiro.test(trees$ln.Volume)
shapiro.test(trees$sqrt.Volume)
```



```{r}
wilcox.test(extra~group, data = sleep)
```

```{r}
wilcox.test(extra~group, data = sleep, paired = TRUE)
```











