---
title: "Week 6 Recitation In Class"
output: html_notebook
---


```{r}

library(pwr)

# what sample size is necessary given we want an effect size of 0.5, and the standard significance level of 0.05 and a power of 0.8?

pwr.t.test(n = NULL, d = 0.5, sig.level=0.05, power =0.9, type="two.sample", alternative="two.sided")

# n is minimum sample size in EACH group to be 90% sure that we are not making a type 2 error and at least 95% sure we are not making a type 1 error. 
pwr.t.test(n = 20, d = 0.5, sig.level=0.05, power= NULL, type="two.sample", alternative="two.sided")


# If we interested, in power 2 (probability of not making a type 2 error)

effect.size<-seq(0, 5, length.out=50)
effect.size

i = 1

test<-pwr.t.test(n = 20, d = effect.size[i], sig.level=0.05, power= NULL, type="two.sample", alternative="two.sided")

test$power
names(test)

i = 3

power<-NA
for(i in 1:50){ # we want i to be 1:50
    
   test<- pwr.t.test(n = 20, d = effect.size[i], sig.level=0.05, power= NULL, type="two.sample", alternative="two.sided")
   power[i]<-test$power

   }

plot(effect.size, power, type="l")

sample <- NA
for(i in 4:50){ # we want i to be 1:50
    
   test<- pwr.t.test(n = NULL, d = effect.size[i], sig.level=0.05, power = 0.8, type="two.sample", alternative="two.sided")
   sample[i]<-test$n

   }




```


```{r}

data(sleep)

library(dplyr)

stats <- sleep %>% group_by(group) %>% summarise(mean = mean(extra),
                                                 sd = sd(extra))
stats

pooled.sd <- sqrt((stats$sd[1]^2 + stats$sd[2]^2 )/2)
effect.size <- abs(stats$mean[1]-stats$mean[2])/pooled.sd

effect.size

pwr.t.test(n = 20, d = effect.size, sig.level = 0.05, power = NULL, type="two.sample", alternative="two.sided")

```
```{r}
with(sleep, t.test(extra~group, paired = TRUE, var.equal = TRUE))
with(sleep, t.test(extra~group, paired = TRUE, var.equal = FALSE))
#equal/separate variances doesn't matter for paired tests!(i think)
```

